### PR TITLE
Fix viewer editor permissions

### LINKED ISSUE #315: Delete command from sidebar list
Missing a easy fast DELETE command. Maybe in the side bar menu ...

### PR DESCRIPTION
**Pull request by skjnldsv**
image

Fix #315

### CODE REVIEW

File: src/services/DavRequest.js [hunk 1]
```diff
@@ -20,17 +20,19 @@
...
+	<d:resourcetype />
 	<nc:face-detections />
+	<nc:file-metadata-size />
+	<nc:has-preview />
+	<nc:realpath />
 	<oc:favorite />
-	<d:resourcetype />`
+	<oc:fileid />
+	<oc:permissions />
+`
```
Comment (artonge) [inline src/services/DavRequest.js:35]: Any reason for the reordering ? just curious :)

**Review by artonge — APPROVED** [review]

File: src/services/DavRequest.js (hunk 1 above)
Comment (marcelklehr) [reply src/services/DavRequest.js:35]: just to mess with us :D

**Comment by marcelklehr** [comment]
Would this be needed for the tags and people views as well?

**Comment by artonge** [comment]
@skjnldsv ^

File: src/services/DavRequest.js (hunk 1 above)
Comment (skjnldsv) [reply src/services/DavRequest.js:35]: Sorting alphabetically

**Comment by skjnldsv** [comment]
> Would this be needed for the tags and people views as well?

Only if you open media on Viewer from those views :shrug:

**Comment by marcelklehr** [comment]
> Only if you open media on Viewer from those views

that's probably a yes...

File: lib/Controller/AlbumsController.php [hunk 2]
```diff
@@ -109,13 +110,36 @@ private function formatData(iterable $nodes): array {
 				'mime' => $node->getMimetype(),
 				'size' => $node->getSize(),
 				'type' => $node->getType(),
+				'permissions' => $this->formatPermissions($node->getPermissions()),
```
Comment (marcelklehr) [inline lib/Controller/AlbumsController.php:113]: Ah, and this is not the albums controller but the folders controller, probably, then we may need this for the actual albums as well

Comment (skjnldsv) [reply lib/Controller/AlbumsController.php:113]: Yep, but the other Views are importing `src/services/DavRequest.js`, so they will benefit from that too

Comment (skjnldsv) [reply lib/Controller/AlbumsController.php:113]: https://github.com/nextcloud/photos/search?q=DavRequest

Comment (marcelklehr) [reply lib/Controller/AlbumsController.php:113]: Yes, but Albums and Faces dav endpoints do not expose permissions in DAV afaik
