### PR TITLE
Fix sharing with group

### LINKED ISSUE #1596: [Bug] Sharing Albums with Groups Doesn't Work
**Describe the bug**
When you share an album with a group of users, those users cannot add photos to the album. My server's been crashing when trying to do this.

**To Reproduce**
1. Create a user group
2. Create a photo album
3. Share the album with the user group
4. Try to add a photo to the shared album as a member of the user group that is not the album owner

**Expected behavior**
Members of user groups with shared permissions should be able to add photos.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Any (tested with Firefox and Brave)
 - Version: n/a

**Smartphone (please complete the following information):**
- n/a

**Additional context**
When sharing with an individual user instead of a user group, this works as expected.

### PR DESCRIPTION
**Pull request by simonspa**
This MR fixes adding photos to an album shared to a group of users. The essential problem was that only collaboration via `userId` was checked.

This adds a new method to `AlbumMapper` to check for any given user ID of the user is a collaborator, no matter whether this is via direct sharing or group sharing.

This fixes #1596

### CODE REVIEW

File: lib/Album/AlbumMapper.php [hunk 1]
```diff
@@ -332,6 +332,40 @@ public function getCollaborators(int $albumId): array {
...
+		$query->select("collaborator_id", "collaborator_type")
+			->from("photos_albums_collabs")
+			->where($query->expr()->eq('album_id', $query->createNamedParameter($albumId, IQueryBuilder::PARAM_INT)));
+
+		$rows = $query->executeQuery()->fetchAll();
+
+		foreach ($rows as $row) {
+			switch ($row['collaborator_type']) {
+				case self::TYPE_USER:
+					if (!strcmp($row['collaborator_id'], $userId)) {
```
Comment (artonge) [inline lib/Album/AlbumMapper.php:352]: Why not use `===` instead of `strcmp` ?

Comment (simonspa) [reply lib/Album/AlbumMapper.php:352]: No particular reason, I've seen `strcmp` being used elsewhere in similar situations. Shall I change it?

Comment (artonge) [reply lib/Album/AlbumMapper.php:352]: Yes, as it is more readable with `===`.
I only used `strcmp` for comparison during array sorting :).

Comment (simonspa) [reply lib/Album/AlbumMapper.php]: Done :)

**Review by artonge — APPROVED** [review]
:rocket:
