### PR TITLE
Fix Timeline state management between routes

### LINKED ISSUE #856: Duplicate key for videos
### Steps to reproduce

1. Setup stable22 from scratch and compile with `make dev-setup && make watch-js`
2. Enable the "Movie" preview provider
3. Upload two videos in the files app
4. Go to the photos app
5. Click on "Your videos"
6. Open the JS console
7. Switch back to "Your photos"

### Expected result
Only 2 videos visible in both "Your photos" and "Your videos"

### Actual result
At first when in "Your photos" only two videos appear.
After switching to "Your videos", there are 4 videos and Duplicate key errors.
And switching back to "Your photos" keeps the 4.

image

### Versions
server stable22 389123ac3c17a09759ef78571417f4819fc16884 
photos stable22 4142e5a64d1a57caf234153860641d36df5ec615

regression status unknown

### LINKED ISSUE #892: Duplicates appear after switching sidebar tabs
**Describe the bug**
Photo thumbnails are duplicated after switching tabs. The only way to fix it, is to reload the page.

**To Reproduce**
1. Go to Photos
2. Click on 'Tagged photos'
3. Switch back to 'Your photos'
4. See an error

**Expected behavior**
Photo tiles are the same as in step 1. 

**Screenshots**
Screenshot from 2021-09-25 13-38-42

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Browser: Firefox 90.0
 - Version: Nextcloud 22 snap

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Browser log**
```
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
photos
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:35:9
No OC found main.js:160:149063
JQMIGRATE: Migrate is installed, version 3.3.2 main.js:986:933
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. main.js:1385:3603
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. main.js:1385:3603
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. main.js:1385:3603
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. main.js:1385:3603
OCA.Files.Sidebar initialized sidebar.js:269:261
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1385:3603
OCA.Comments.View initialized comments-app.js:573:362
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 2 main.js:1385:3603
OCA.Sharing.ShareSearch initialized files_sharing_tab.js:1352:199
OCA.Sharing.ExternalLinkActions initialized files_sharing_tab.js:1374:199
Proxying an event bus of version 1.3.0 with 2.0.0 viewer-main.js:2:536200
OCA.Viewer initialized viewer-main.js:2:679363
No OCA.Files app found, viewer is now in standalone mode viewer-main.js:2:619576
Proxying an event bus of version 1.3.0 with 2.0.0 richdocuments-viewer.js:2:319260
OC.getCapabilities is deprecated and will be removed in Nextcloud 21. See @nextcloud/capabilities main.js:137:3576
Service Worker is not enabled on this browser. photos-main.js:2:832481
[photos] Grid config 
Object { marginTop: 88, marginW: 66, count: 6, gap: 8 }
photos-main.js:2:883711
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 main.js:1385:3603
Proxying an event bus of version 1.3.0 with 2.0.0 notifications-main.js:2:415245
Loading theming data for notification bell styling notifications-main.js:2:428615
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. main.js:1385:3603
Registering notifications container as a menu notifications-main.js:2:428851
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 main.js:1385:3603
Notifications require HTTPS notifications-main.js:2:433719
Polling interval updated to 30000 notifications-main.js:2:432950
Started background fetcher as session_keepalive is enabled notifications-main.js:2:430241
Please do NOT wait for the DOMContentLoaded before registering your viewer handler viewer-main.js:2:618196
The following mime is already registered text/csv 
Object { id: Getter & Setter, group: Getter & Setter, mimes: Getter & Setter, component: Getter & Setter, … }
viewer-main.js:2:623279
session heartbeat polling started main.js:822:971
Please do NOT wait for the DOMContentLoaded before registering your viewer handler viewer-main.js:2:618196
Got notification data notifications-main.js:2:431963
Polling interval updated to 30000 notifications-main.js:2:432950
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 main.js:1385:3603
New notification, animating the bell icon notifications-main.js:2:429602
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
unified-search.js:32:64313
oc_defaults is deprecated: use OC.theme instead, this will be removed in Nextcloud 20 main.js:1385:3603
Got notification data notifications-main.js:2:431963
Polling interval updated to 30000 notifications-main.js:2:432950
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 8 main.js:116:2282
Got notification data notifications-main.js:2:431963
Polling interval updated to 30000 notifications-main.js:2:432950
Error fetching timeline 
Object { message: "Changed view" }
photos-main.js:2:848738
Could not get the error illustration Error: Cannot find module '../assets/Illustrations/empty.svg'
    e http://94.158.81.70/apps/photos/js/photos-main.js?v=3c1e5c5e:2
    t http://94.158.81.70/apps/photos/js/photos-main.js?v=3c1e5c5e:2
photos-main.js:2:834082
Error fetching timeline 
Object { message: "Changed view" }
photos-main.js:2:848738
Could not get the error illustration Error: Cannot find module '../assets/Illustrations/empty.svg'
    e http://94.158.81.70/apps/photos/js/photos-main.js?v=3c1e5c5e:2
    t http://94.158.81.70/apps/photos/js/photos-main.js?v=3c1e5c5e:2
photos-main.js:2:834082
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://94.158.81.70/apps/files/js/dist/sidebar.js?v=3c1e5c5e
Source Map URL: sidebar.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://94.158.81.70/core/js/dist/main.js?v=3c1e5c5e
Source Map URL: main.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://94.158.81.70/extra-apps/richdocuments/js/richdocuments-viewer.js?v=3c1e5c5e
Source Map URL: richdocuments-viewer.js.map?v=d391bfcbaaba0add2ab6

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://94.158.81.70/apps/comments/js/comments-app.js?v=3c1e5c5e
Source Map URL: comments-app.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://94.158.81.70/apps/files_sharing/js/dist/files_sharing_tab.js?v=3c1e5c5e
Source Map URL: files_sharing_tab.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://94.158.81.70/apps/photos/js/photos-main.js?v=3c1e5c5e
Source Map URL: photos-main.js.map?v=cad524754d37ae916409

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://94.158.81.70/apps/viewer/js/viewer-main.js?v=3c1e5c5e
Source Map URL: viewer-main.js.map?v=e90c2feca473d3bb80b3

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://94.158.81.70/apps/notifications/js/notifications-main.js?v=3c1e5c5e
Source Map URL: notifications-main.js.map?v=3cccdf405849d223e62d

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://94.158.81.70/core/js/dist/unified-search.js?v=3c1e5c5e
Source Map URL: unified-search.js.map
```

**Additional context**
This bug occurs regardless of browser.

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #892
fixes #856

The problem was that the grid will trigger a fetch on its own if it's already mounted, so the watchers are redundant. Setting loading to false initially will render the grid and it will trigger the first fetch on initial page load as well as after any route changes. the $route watcher and the beforeRouteLeave hook then only take care of resetting and cancelling excess requests.

### CODE REVIEW

File: src/Photos.vue [hunk 1]
```diff
@@ -91,7 +91,7 @@ export default {
 	},
 	data() {
 		return {
-			loading: true,
+			loading: false,
```
Comment (marcelklehr) [inline src/Photos.vue:94]: This makes sure the grid is rendered on initial load. It will then load the first batch on its own.

**Review by Mikescops — APPROVED** [review]
Ok sounds good

File: src/views/Timeline.vue [hunk 2]
```diff
@@ -177,32 +178,34 @@ export default {
...
-			this.getContent()
-		},
-		async mimesType() {
-			// reset component
+		$route(from, to) {
+			// cancel any pending requests
+			if (this.cancelRequest) {
+				this.cancelRequest('Changed view')
+			}
 			this.resetState()
```
Comment (skjnldsv) [inline src/views/Timeline.vue:186]: Where do we `getContent` now?

Comment (marcelklehr) [reply src/views/Timeline.vue:186]: See above comment:

> This makes sure the grid is rendered on initial load. It will then load the first batch on its own.

**Review by skjnldsv — APPROVED** [review]
