### PR TITLE
Fix default previews

### LINKED ISSUE #909: No default thumbnail for video files when preview provider for video files is not enabled
**Describe the bug**
I still have the issue described in https://github.com/nextcloud/photos/issues/854, even after installing Nextcloud 22.2.0, which in theory contains https://github.com/nextcloud/photos/pull/876 which is supposed to fix the issue.
The default thumbnail is not displayed for video files (.mp4), with the Movie or MP4 preview provider disabled.

**To Reproduce**
Do not modify the default NC list of enabled preview providers (i.e. Movie and MP4 preview providers are not enabled)
Upload some .mp4 video files to NC
Open https://server_url/apps/photos/ or https://server_url/apps/photos/videos

**Expected behavior**
I expect to see the default svg image for video files, which we can correctly see when we browse to https://server_url/apps/files (i.e. a "play" icon inside a square)

**Screenshots**
NC 19.0.13 html code (default thumbnail is ok):
Nextcloud_bug_photos_app_video_previews_NC19_OK

NC 22.2.0 html code:
Nextcloud_bug_photos_app_video_previews_NC22 2 0_KO

NC 22.2.0 appearance:
Nextcloud_bug_photos_app_video_previews_NC22 2 0_KO_appearance

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 78.15esr and Edge Chromium

**Browser log**
[photos] Grid config Object { marginTop: 88, marginW: 66, count: 7, gap: 8 }
SW registration failed:  TypeError: ServiceWorker script at https://server_url/apps/photos/service-worker.js for scope https://server_url/ encountered an error during installation. Photos.vue:114

**Additional context**
NC 22.2.0
Photos 1.4.0
PHP 7.4.23
S3 as primary storage

### PR DESCRIPTION
**Pull request by st3iny**
Fix #909

Some default preview SVGs are not shown correctly because they are imported using the wrong loader. In some places (ref https://github.com/nextcloud/photos/pull/842) this has already been fixed.

I changed some webpack rules to force the usage of `raw-loader` for all SVGs to bypass the `!raw-loader!...` hack. This is needed because they are inserted using `v-html` and the default loader (`asset/inline`) from our shared config produces `data:image/svg+xml` blobs.

**PS:** The attribute `xlink:href` is deprecated in favor of just `href` (ref https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href). 

| Illustrations (still working) | Default previews (now fixed) |
| --- | --- |
| Screenshot 2022-01-07 at 10-36-58 Photos - Nextcloud | Screenshot 2022-01-07 at 10-36-49 Photos - Nextcloud |

### CODE REVIEW

File: webpack.js [hunk 1]
```diff
@@ -29,6 +29,15 @@ webpackRules.RULE_SCSS.use = [
 	},
 ]
 
+// Load raw SVGs to be able to inject them via v-html
+webpackRules.RULE_ASSETS.test = /\.(png|jpe?g|gif|woff2?|eot|ttf)$/
+webpackRules.RULE_RAW_SVGS = {
```
Comment (skjnldsv) [inline webpack.js:34]: Fancy :heart_eyes: 
Love that we can do that and it stays clean!

**Review by skjnldsv — APPROVED** [review]
